# /docker-compose.yaml (raiz do projeto)
name: bk_998877

services:
  
  # postgres:
  #   container_name: ${COMPOSE_PROJECT_NAME}-db
  #   image: postgres:15.6
  #   hostname: "postgres"
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #     POSTGRES_USER: ${DATABASE_USER}
  #     POSTGRES_DB: ${DATABASE_DB}
  #   networks:
  #     - backend
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   ports:
  #     - '${DATABASE_POST}:${DATABASE_POST}'
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: '1.0GB'

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    build:
      context: .
      dockerfile: Dockerfile
      # Require: `.env.BUILD_TARGET`
      target: ${BUILD_TARGET:-dev}
    restart: unless-stopped
    # depends_on:
    #   - "postgres"
    networks:
      - backend
    environment:
      - PORT=${APP_PORT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - '${APP_PORT}:${APP_PORT}'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'

networks:
  backend:

# volumes:
#   postgres-data:
