name: bk_998877-dev

services:

  app:
    container_name: ${COMPOSE_PROJECT_NAME}-app
    build:
      # equals: `cd ../`
      context: ../
      dockerfile: .devcontainer/Dockerfile
    restart: no
    # network_mode: host
    # extra_hosts:
    # - "host.docker.internal:host-gateway"
    networks:
      - backend
    volumes:
      - ../..:/workspaces:cached
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '1.0GB'

  # postgres:
  #   container_name: ${COMPOSE_PROJECT_NAME}-db
  #   image: postgres:15.4
  #   restart: on-failure
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #     POSTGRES_DB: postgres
  #   networks:
  #     - backend
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.5'
    #       memory: '1.0GB'

networks:
  backend:

volumes:
  postgres-data:
