name: Deploy
on:
  workflow_run:
    workflows: [Merge main]
    types:
      - completed
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉"
      # - uses: actions/checkout@v2
      # - uses: akhileshns/heroku-deploy@v3.12.13
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "api-doc-doc"
      #     heroku_email: "cdonat@findes.org.br"
