name: Create pre-release
on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+-[0-9]+"

jobs:
  pre-release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
