name: test-build-application
run-name: Test Build application

on:
  workflow_run:
    workflows:
      - "trigger-new-release"
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # -
      #   name: Build
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: false

      - name: Build images
        run: docker compose -f docker-compose.yaml build

      - name: Up image
        run: docker compose -f docker-compose.prod.yml up
        # run: docker compose up -f docker-compose.yaml --build
